services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE # The cap_add set to SYS_NICE suppresses some not useful error messages.
    restart: always
    environment:
      MYSQL_DATABASE: 'property_management'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app-server:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/property_management'
      SPRING_DATASOURCE_USERNAME: 'user'
      SPRING_DATASOURCE_PASSWORD: 'password'
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
